### PR TITLE
feat: opt-in automatic responsive view support for `asImageWidthSrcSet()`

### PR DESCRIPTION
**Pull request by angeloashmore**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR updates `asImageWidthSrcSet()` to make automatic responsive view support opt-in. Without the changes introduced here, there is no way to opt-out of automatic responsive view support without altering the field's data manually.

Before this PR:

```typescript
asImageWidthSrcSet(fieldWithThumbnails).srcset;
// => A `srcset` value with each thumbnail used as an image URL.

// There is no way to opt-out of automatic responsive view support.
```

After this PR:

```typescript
asImageWidthSrcSet(fieldWithThumbnails).srcset;
// => A `srcset` value for the base image.

asImageWidthSrcSet(fieldWithThumbnails, { widths: "thumbnails" }).srcset;
// => A `srcset` value with each thumbnail used as an image URL.
```

**Important!**: This is technically a breaking change. However, I think we can move forward as a minor version since this is a relatively new API and usage is likely low.

To restore the previous automatic responsive view functionality, pass `"thumbnails"` to the `widths` parameter, like the following example:

```typescript
// Old
asImageWidthSrcSet(fieldWithThumbnails);

// New
asImageWidthSrcSet(fieldWithThumbnails, { widths: "thumbnails" });
```

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

🦌

### CODE REVIEW

**Review by lihbr — COMMENTED** [review]
Code looks good to me 🎉

**Sidenotes**

I have mixed feelings about making it _opt-in_. On one hand it makes it less surprising (because your responsive views might be for a completely different purpose), on the other way it doesn't promote using responsive views. 🤔 I think I lean toward this approach of opting-in (so this PR's approach).

About the reason why I picked `"auto"` instead of `"thumbnails"` for the Vue component was because `"thumbnails"` was less memorable (and we also call those "responsive views" at some places), but maybe `"auto"` makes it convey less meaning. I don't have a strong opinion again though and can still update the Vue/11ty kits. Really naming thing sucks ^^'

**Comment by angeloashmore** [comment]
Awesome, thanks for the review!

> I have mixed feelings about making it opt-in.

My only concern is that dimensions for thumbnails/responsive views may not always align with that you want on a page. In the editor, you may just want to make it possible to provide different images for Desktop, Tablet, and Mobile, but at the highest resolution available. Imgix + `<PrismicImage>`/`asImageWidthSrcSet()` will take care of resizing it down to the correct size.

This is especially true if you need to support high DPI (which should be everyone). Setting a thumbnail width of `420px`, for example, really needs an image width of at least `840px`.

In other words, this lets someone treat thumbnails as different source images, without tying its dimensions to the website.

Now, if someone wants to treat thumbnails sizes as the final width, they can declare that with `widths: "thumbnails"`.

That's my thinking. LMK if you have a differing view. Maybe there's a different API we could come up with to address this?

> About the reason why I picked "auto" instead of "thumbnails" for the Vue component was because "thumbnails" was less memorable (and we also call those "responsive views" at some places), but maybe "auto" makes it convey less meaning.

To me, `auto` could mean things like checking the container's size to determine target image dimensions. Same for a name like `responsive`. `thumbnails`, to me, is a bit more descriptive in that it says it will use the field's thumbnail sizes.

**Comment by lihbr** [comment]
Sure, makes sense to me! Let's go ahead this way I'll update the Vue API :relaxed:

**Comment by angeloashmore** [comment]
Awesome, thanks! I'll merge it now, but I'll hold off on publishing for now.

If we need to publish a bug fix, it can be published then. Otherwise, I'll publish before `@prismicio/react`'s `<PrismicImage>` is published.

**Pull request merged**
